# Generated by Django 4.2.4 on 2023-08-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['musician'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name'], 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AddField(
            model_name='song',
            name='musician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.musician', verbose_name='Исполнитель'),
            preserve_default=False,
        ),
    ]
