# Generated by Django 4.2.4 on 2023-08-29 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_album_options_alter_song_options_song_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.album', verbose_name='Альбом'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Порядковый номер в альбоме'),
        ),
    ]
