# Generated by Django 4.2.4 on 2023-08-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_song_album_alter_song_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Название альбома'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Порядковый номер в альбоме'),
        ),
    ]
