# Generated by Django 4.2.4 on 2023-08-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_album_name_alter_song_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Порядковый номер в альбоме'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('album', 'number'), name='unique_album_number'),
        ),
    ]
